#index:
#    path: /
#    controller: App\Controller\DefaultController::index
welcome:
  path: /welcome
  controller: App\Controller\WelcomeController::hello

product-category:
    path: /product-category
    controller: App\Controller\ProductCategoryController::index