index:
    path: /
    controller: App\Controller\LocalController::hello
welcome:
  path: /welcome
  controller: App\Controller\WelcomeController::hello

product-category:
    path: /product-category
    controller: App\Controller\ProductCategoryController::index

product:
  path: /product
  controller: App\Controller\ProductController::index