index:
    path: /
    controller: App\Controller\LocalController::hello
welcome:
  path: /welcome
  controller: App\Controller\WelcomeController::hello

product-category:
    path: /product-category
    controller: App\Controller\ProductCategoryController::index

product:
  path: /product
  controller: App\Controller\ProductController::index

library:
    path: /library
    controller: App\Controller\LocalLibraryController::hello

ksiazki:
  path: /ksiazka
  controller: App\Controller\KsiazkaController::index

autor:
  path: /autor
  controller: App\Controller\AutorController::index

gatunki:
  path: /gatunek
  controller: App\Controller\GatunekController::index